### PR TITLE
Adds IBM JDK package to optional dependencies

### PR DESCRIPTION
**Pull request by colindean**

### CODE REVIEW

**Comment by colindean** [comment]
I need to test to make sure 100% that this works, which I will do shortly.

**Comment by colindean** [comment]
I'll have to pick this back up tomorrow. Ran into a network issue that prevented me from actually installing the IBM JDK to test this...

**Comment by trygvis** [comment]
Are you sure that `ibm-j2sdk1.7` is the correct name of the package? I can't find much info about it when I search for it.

**Comment by colindean** [comment]
100% certain. Looked on a coworker's machine as I did this commit ;-)

**Comment by trygvis** [comment]
Strange, Google gives me exactly 1 hit for "ibm-j2sdk1.7". Anyway, it can't hurt so I'll merge it.

**Pull request merged**
